# Generated by Django 3.2.8 on 2021-11-16 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthentication', '0002_auto_20211116_1636'),
        ('Tutor', '0003_auto_20211116_1638')
    ]

    operations = [
        migrations.DeleteModel(
            name='TutorCourse',
        ),
    ]
