# Generated by Django 3.2.5 on 2021-11-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Region', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regions',
            name='country',
            field=models.CharField(default='Costa Rica', max_length=20),
            preserve_default=False,
        ),
    ]
