# Generated by Django 3.2.8 on 2021-11-01 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Resource', '0001_initial'),
        ('Tutorship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcetutorship',
            name='tutorship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tutorship.tutorship'),
        ),
    ]
