# Generated by Django 3.2.8 on 2021-11-19 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthentication', '0003_delete_tutorcourse'),
        ('Resource', '0003_alter_resource_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserAuthentication.user'),
        ),
    ]
