# Generated by Django 3.2.8 on 2021-11-16 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseKeyword',
        ),
    ]
