# Generated by Django 3.2.8 on 2021-11-01 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_people', models.IntegerField()),
                ('state', models.CharField(choices=[('AP', 'Aprobada'), ('DN', 'Realizada')], default='AP', max_length=2)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=250)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.request')),
            ],
        ),
        migrations.CreateModel(
            name='TutorshipScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('tutorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutorship.tutorship')),
            ],
        ),
    ]
