# Generated by Django 3.2.5 on 2021-11-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorshipscore',
            name='student_comment',
            field=models.TextField(null=True),
        ),
    ]
