# Generated by Django 3.2.8 on 2021-11-13 16:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
        ('UserAuthentication', '0001_initial'),
        ('Tutorship', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('RE', 'Nueva solicitud'), ('AR', 'Solicitud aceptada'), ('RR', 'Solicitud rechazada')], max_length=2)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('seen', models.BooleanField(default=False)),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='UserAuthentication.user')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.request')),
                ('to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='UserAuthentication.user')),
            ],
        ),
    ]
