# Generated by Django 3.2.8 on 2021-11-16 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorship', '0002_requestnotification'),
        ('Tutorship', '0002_tutorshipscore_student_comment'),
    ]

    operations = [
    ]
