# Generated by Django 3.2.8 on 2021-11-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorship', '0003_merge_20211116_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorship',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
