# Generated by Django 3.2.8 on 2021-11-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorship', '0004_tutorship_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorship',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tutorship',
            name='name',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
