# Generated by Django 3.2.8 on 2021-11-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorship', '0005_auto_20211118_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorship',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
