# Generated by Django 3.2.8 on 2021-11-25 00:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthentication', '0003_delete_tutorcourse'),
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('NM', 'New Message'), ('NR', 'New Reply')], max_length=2)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('seen', models.BooleanField(default=False)),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_from', to='UserAuthentication.user')),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Chat.message')),
                ('to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to='UserAuthentication.user')),
            ],
        ),
    ]
