# Generated by Django 3.2.8 on 2021-11-01 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Session', '0001_initial'),
        ('UserAuthentication', '0001_initial'),
        ('Modality', '0001_initial'),
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorAvailableSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAuthentication.user')),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_per_person', models.IntegerField(default=0)),
                ('increment_per_half_hour', models.IntegerField(default=0)),
                ('modality_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Modality.modality')),
                ('payment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Payment.payment')),
                ('session_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Session.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAuthentication.user')),
            ],
        ),
    ]
