# Generated by Django 3.2.8 on 2021-11-16 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthentication', '0002_auto_20211116_1636'),
        ('Course', '0002_delete_coursekeyword'),
        ('Tutor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAuthentication.user')),
            ],
        ),
    ]
