# Generated by Django 3.2.8 on 2021-11-16 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0002_tutorcourse'),
    ]

    operations = [
        migrations.RunSQL("""
                SET IDENTITY_INSERT tutor_tutorcourse ON;
                INSERT INTO tutor_tutorcourse (
                    id,
                    user_id,
                    course_id
                )
                SELECT
                    id,
                    user_id,
                    course_id
                FROM
                    userauthentication_tutorcourse;
            """, reverse_sql="""
                INSERT INTO userauthentication_tutorcourse (
                    id,
                    user_id,
                    course_id
                )
                SELECT
                    id,
                    user_id,
                    course_id
                FROM
                    tutor_tutorcourse;
            """)
    ]
