# Generated by Django 3.2.8 on 2021-11-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0003_auto_20211116_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='average_rating',
            field=models.IntegerField(default=0),
        ),
    ]
