# Generated by Django 3.2.5 on 2021-11-29 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Region', '0002_regions_country'),
        ('Tutor', '0004_tutor_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Region.regions'),
        ),
    ]
