# Generated by Django 3.2.5 on 2021-11-29 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Region', '0002_regions_country'),
        ('Tutor', '0005_tutor_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Region.regions'),
        ),
    ]
