# Generated by Django 3.2.5 on 2021-12-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modality', '0001_initial'),
        ('Payment', '0001_initial'),
        ('Session', '0001_initial'),
        ('Tutor', '0006_alter_tutor_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='modality_type',
        ),
        migrations.AddField(
            model_name='tutor',
            name='modality_type',
            field=models.ManyToManyField(to='Modality.Modality'),
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='tutor',
            name='payment_type',
            field=models.ManyToManyField(to='Payment.Payment'),
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='session_type',
        ),
        migrations.AddField(
            model_name='tutor',
            name='session_type',
            field=models.ManyToManyField(to='Session.Session'),
        ),
    ]
