# Generated by Django 3.2.8 on 2021-11-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='num_requesters',
            field=models.IntegerField(default=1),
        ),
    ]
